app:
  db: micro-operaciones-empresarial
server:
  port: 8082
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: banco
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
      configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 50s
            failureRateThreshold: 20
            eventConsumerBufferSize: 10
      instances:
        ms3:
          base-config: default
  timelimiter:
    instances:
      ms3:
        timeout-duration: 2s
        cancel-running-future: true